on: push
jobs:
  cpe:
    runs-on: ubuntu-latest
    steps:
      - name: checkout fleet
        uses: actions/checkout@v2
        with:
          repository: fleetdm/fleet
          fetch-depth: 1
          ref: issue-1435-software-to-cpe
          token: ${{ github.token }}
      - name: run generate
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.4'
      - name: generate cpe sqlite
        run: go mod download && go run cmd/nvd/generate.go